import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/sidebar";
import { SiteHeader } from "@/components/header";
import QueryProvider from "@/provider/queryProvider";
import { ThemeProvider } from "@/provider/themeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NanoImg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
         attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
        <QueryProvider>
        <SidebarProvider>
          <AppSidebar />

        <main className="flex flex-col w-full h-screen ">
          
          <SiteHeader />
          {children}
        </main>
        </SidebarProvider>
        </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
